apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-youssef
  labels:
    app: node-redis-youssef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-redis-youssef
  template:
    metadata:
      labels:
        app: node-redis-youssef
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: node-redis-youssef
          image: cloud.canister.io:5000/arhturescriou/node-redis
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: REDIS_URL
              value: "redis://redis-service-youssef:6379"
